version: 0.2

phases:
  install:
    runtime-versions:
      runtime: 'nodejs: 14'
    on-failure: ABORT
    commands:
      - npm install
  build:
    on-failure: ABORT
    commands:
      - npm run test:pact
